<a href="https://colab.research.google.com/github/Swaraj-sj2000/Machine-leaning-projects/blob/main/rev2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
import tensorflow as tf
print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

TensorFlow: 2.19.0
GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [111]:
import json
kaggle_dict={'username':'sjrohan',
             'key':'KGAT_931103ac2d60512613022382987768cb'}
with open('kaggle.json','w') as f:
  json.dump(kaggle_dict,f)

In [112]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [113]:
!pip install -q kaggle

In [114]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

movies_df= kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "tmdb/tmdb-movie-metadata",
    "tmdb_5000_movies.csv"
)

/tmp/ipykernel_7227/3358068137.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  movies_df= kagglehub.load_dataset(

Using Colab cache for faster access to the 'tmdb-movie-metadata' dataset.

In [115]:
credits_df= kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "tmdb/tmdb-movie-metadata",
    "tmdb_5000_credits.csv"
)

/tmp/ipykernel_7227/3042225847.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  credits_df= kagglehub.load_dataset(

Using Colab cache for faster access to the 'tmdb-movie-metadata' dataset.

In [143]:
import numpy as np
import pandas as pd
movies=movies_df.copy()
credits=credits_df.copy()

In [117]:
print(movies.shape)
print(credits.shape)

(4803, 20)
(4803, 4)

In [145]:
movies=movies.merge(credits,on='title')

In [119]:
print(movies.shape)

(4809, 23)

In [120]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [146]:
movies.drop(columns=['budget','homepage','production_countries','original_title','popularity','production_companies','production_countries','runtime','spoken_languages','status','tagline','movie_id'],inplace=True)

In [122]:
print(movies.shape)
print(movies.info())

(4809, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   genres             4809 non-null   object
 1   id                 4809 non-null   int64
 2   keywords           4809 non-null   object
 3   original_language  4809 non-null   object
 4   overview           4806 non-null   object
 5   release_date       4808 non-null   object
 6   revenue            4809 non-null   int64
 7   title              4809 non-null   object
 8   vote_average       4809 non-null   float64
 9   vote_count         4809 non-null   int64
 10  cast               4809 non-null   object
 11  crew               4809 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 451.0+ KB
None

In [123]:
movies.isnull().sum()

genres               0
id                   0
keywords             0
original_language    0
overview             3
release_date         1
revenue              0
title                0
vote_average         0
vote_count           0
cast                 0
crew                 0
dtype: int64

In [147]:
movies.dropna(subset=['overview','release_date'],inplace=True)

In [125]:
movies.duplicated().sum()

np.int64(0)

In [126]:
print(movies.iloc[0]['genres'])

[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]

In [148]:
import ast
cols = ['genres','keywords','cast','crew']
for col in cols:
  movies[col] = movies[col].apply(ast.literal_eval)

In [149]:
movies.head(2)

,genres,id,keywords,original_language,overview,release_date,revenue,title,vote_average,vote_count,cast,crew
0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",19995,"[{'id': 1463, 'name': 'culture clash'}, {'id':...",en,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,2787965087,Avatar,7.2,11800,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",285,"[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...",en,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4232c3a36847f800b579', 'de..."

In [150]:
movies['genres']=movies['genres'].apply(lambda x:[item['name'].replace(' ','_')  for item in x] if isinstance(x,list) else [])
movies['keywords']=movies['keywords'].apply(lambda x:[item['name'].replace(' ','_') for item in x] if isinstance(x,list) else [])
movies['cast']=movies['cast'].apply(lambda x:[item['name'].replace(' ','_') for item in x] if isinstance(x,list) else [][:3])

In [151]:
movies.head()

,genres,id,keywords,original_language,overview,release_date,revenue,title,vote_average,vote_count,cast,crew
0,"[Action, Adventure, Fantasy, Science_Fiction]",19995,"[culture_clash, future, space_war, space_colon...",en,"In the 22nd century, a paraplegic Marine is di...",2009-12-10,2787965087,Avatar,7.2,11800,"[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug_abuse, exotic_island, east_india_...",en,"Captain Barbossa, long believed to be dead, ha...",2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...","[{'credit_id': '52fe4232c3a36847f800b579', 'de..."
2,"[Action, Adventure, Crime]",206647,"[spy, based_on_novel, secret_agent, sequel, mi...",en,A cryptic message from Bond’s past sends him o...,2015-10-26,880674609,Spectre,6.3,4466,"[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...","[{'credit_id': '54805967c3a36829b5002c41', 'de..."
3,"[Action, Crime, Drama, Thriller]",49026,"[dc_comics, crime_fighter, terrorist, secret_i...",en,Following the death of District Attorney Harve...,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,"[Christian_Bale, Michael_Caine, Gary_Oldman, A...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de..."
4,"[Action, Adventure, Science_Fiction]",49529,"[based_on_novel, mars, medallion, space_travel...",en,"John Carter is a war-weary, former military ca...",2012-03-07,284139100,John Carter,6.1,2124,"[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de..."

In [152]:
print(movies['cast'].head())

0    [Sam_Worthington, Zoe_Saldana, Sigourney_Weave...
1    [Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...
2    [Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...
3    [Christian_Bale, Michael_Caine, Gary_Oldman, A...
4    [Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...
Name: cast, dtype: object

In [132]:
for items in ['genres','cast','keywords']:
  check_len=list(movies.loc[movies[items].apply(len)==0].index)
  print(check_len)
  print(len(check_len))

[3976, 3997, 4073, 4110, 4123, 4299, 4320, 4391, 4406, 4419, 4464, 4510, 4556, 4568, 4572, 4575, 4577, 4587, 4617, 4628, 4639, 4663, 4680, 4687, 4720, 4722, 4807]
27
[2603, 3674, 3997, 4014, 4073, 4123, 4252, 4311, 4320, 4328, 4407, 4464, 4497, 4510, 4514, 4523, 4556, 4568, 4570, 4572, 4577, 4587, 4589, 4595, 4622, 4623, 4639, 4644, 4663, 4680, 4685, 4691, 4695, 4704, 4716, 4718, 4722, 4743, 4761, 4763, 4803]
41
[71, 83, 323, 381, 436, 605, 678, 857, 866, 881, 966, 967, 982, 1040, 1070, 1073, 1100, 1247, 1259, 1268, 1270, 1278, 1286, 1289, 1307, 1325, 1370, 1466, 1471, 1524, 1546, 1571, 1675, 1694, 1711, 1743, 1757, 1777, 1803, 1836, 1864, 1875, 1921, 1928, 1936, 1964, 1965, 1985, 1988, 2003, 2007, 2012, 2013, 2081, 2083, 2100, 2109, 2112, 2124, 2167, 2176, 2184, 2224, 2228, 2250, 2254, 2258, 2274, 2275, 2294, 2311, 2313, 2319, 2362, 2366, 2381, 2387, 2403, 2412, 2422, 2423, 2429, 2439, 2462, 2496, 2504, 2509, 2533, 2540, 2565, 2579, 2593, 2603, 2613, 2616, 2631, 2636, 2648, 2651, 2660, 2664, 2672, 2681, 2683, 2689, 2697, 2709, 2710, 2730, 2746, 2756, 2763, 2766, 2781, 2791, 2793, 2835, 2853, 2869, 2871, 2881, 2899, 2902, 2903, 2911, 2924, 2934, 2935, 2936, 2966, 2973, 2974, 2975, 2979, 3023, 3024, 3025, 3041, 3062, 3070, 3079, 3081, 3083, 3090, 3092, 3104, 3106, 3115, 3124, 3147, 3157, 3167, 3169, 3188, 3196, 3197, 3202, 3203, 3206, 3208, 3210, 3216, 3228, 3229, 3231, 3246, 3251, 3267, 3271, 3285, 3287, 3289, 3290, 3302, 3307, 3309, 3321, 3322, 3325, 3329, 3338, 3362, 3364, 3380, 3396, 3399, 3403, 3405, 3406, 3415, 3425, 3435, 3440, 3456, 3488, 3489, 3490, 3503, 3506, 3512, 3513, 3520, 3526, 3528, 3531, 3547, 3581, 3594, 3601, 3613, 3626, 3656, 3665, 3669, 3673, 3674, 3678, 3690, 3712, 3719, 3723, 3725, 3734, 3786, 3798, 3803, 3813, 3814, 3841, 3845, 3862, 3893, 3916, 3943, 3948, 3950, 3953, 3962, 3965, 3968, 3972, 3976, 3977, 3981, 3983, 3997, 3998, 4009, 4014, 4032, 4039, 4043, 4045, 4052, 4061, 4062, 4073, 4074, 4075, 4091, 4110, 4116, 4121, 4123, 4128, 4130, 4147, 4148, 4152, 4154, 4165, 4166, 4174, 4189, 4193, 4203, 4210, 4212, 4215, 4217, 4238, 4244, 4252, 4257, 4260, 4261, 4262, 4263, 4267, 4275, 4279, 4291, 4295, 4299, 4311, 4313, 4317, 4320, 4323, 4324, 4328, 4369, 4376, 4383, 4391, 4395, 4406, 4407, 4411, 4419, 4421, 4422, 4423, 4424, 4425, 4427, 4432, 4436, 4456, 4464, 4465, 4472, 4474, 4482, 4493, 4494, 4495, 4496, 4497, 4499, 4506, 4507, 4508, 4510, 4512, 4521, 4528, 4530, 4532, 4547, 4549, 4552, 4556, 4558, 4562, 4565, 4566, 4568, 4570, 4572, 4575, 4577, 4580, 4586, 4589, 4590, 4606, 4607, 4617, 4624, 4628, 4631, 4633, 4635, 4636, 4639, 4640, 4644, 4647, 4650, 4652, 4659, 4661, 4663, 4671, 4673, 4680, 4685, 4688, 4691, 4696, 4698, 4705, 4708, 4720, 4722, 4727, 4735, 4740, 4743, 4749, 4756, 4757, 4760, 4761, 4763, 4766, 4767, 4769, 4770, 4775, 4777, 4783, 4786, 4791, 4796, 4800, 4803, 4805, 4807]
410

In [153]:
movies['empty_features']=(movies['genres'].apply(len)+movies['cast'].apply(len)+movies['keywords'].apply(len))
movies=movies[movies['empty_features']>0]
print(movies.shape)

(4791, 13)

In [134]:
print(movies['crew'][0])

[{'credit_id': '52fe48009251416c750aca23', 'department': 'Editing', 'gender': 0, 'id': 1721, 'job': 'Editor', 'name': 'Stephen E. Rivkin'}, {'credit_id': '539c47ecc3a36810e3001f87', 'department': 'Art', 'gender': 2, 'id': 496, 'job': 'Production Design', 'name': 'Rick Carter'}, {'credit_id': '54491c89c3a3680fb4001cf7', 'department': 'Sound', 'gender': 0, 'id': 900, 'job': 'Sound Designer', 'name': 'Christopher Boyes'}, {'credit_id': '54491cb70e0a267480001bd0', 'department': 'Sound', 'gender': 0, 'id': 900, 'job': 'Supervising Sound Editor', 'name': 'Christopher Boyes'}, {'credit_id': '539c4a4cc3a36810c9002101', 'department': 'Production', 'gender': 1, 'id': 1262, 'job': 'Casting', 'name': 'Mali Finn'}, {'credit_id': '5544ee3b925141499f0008fc', 'department': 'Sound', 'gender': 2, 'id': 1729, 'job': 'Original Music Composer', 'name': 'James Horner'}, {'credit_id': '52fe48009251416c750ac9c3', 'department': 'Directing', 'gender': 2, 'id': 2710, 'job': 'Director', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750ac9d9', 'department': 'Writing', 'gender': 2, 'id': 2710, 'job': 'Writer', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca17', 'department': 'Editing', 'gender': 2, 'id': 2710, 'job': 'Editor', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca29', 'department': 'Production', 'gender': 2, 'id': 2710, 'job': 'Producer', 'name': 'James Cameron'}, {'credit_id': '52fe48009251416c750aca3f', 'department': 'Writing', 'gender': 2, 'id': 2710, 'job': 'Screenplay', 'name': 'James Cameron'}, {'credit_id': '539c4987c3a36810ba0021a4', 'department': 'Art', 'gender': 2, 'id': 7236, 'job': 'Art Direction', 'name': 'Andrew Menzies'}, {'credit_id': '549598c3c3a3686ae9004383', 'department': 'Visual Effects', 'gender': 0, 'id': 6690, 'job': 'Visual Effects Producer', 'name': 'Jill Brooks'}, {'credit_id': '52fe48009251416c750aca4b', 'department': 'Production', 'gender': 1, 'id': 6347, 'job': 'Casting', 'name': 'Margery Simkin'}, {'credit_id': '570b6f419251417da70032fe', 'department': 'Art', 'gender': 2, 'id': 6878, 'job': 'Supervising Art Director', 'name': 'Kevin Ishioka'}, {'credit_id': '5495a0fac3a3686ae9004468', 'department': 'Sound', 'gender': 0, 'id': 6883, 'job': 'Music Editor', 'name': 'Dick Bernstein'}, {'credit_id': '54959706c3a3686af3003e81', 'department': 'Sound', 'gender': 0, 'id': 8159, 'job': 'Sound Effects Editor', 'name': 'Shannon Mills'}, {'credit_id': '54491d58c3a3680fb1001ccb', 'department': 'Sound', 'gender': 0, 'id': 8160, 'job': 'Foley', 'name': 'Dennie Thorpe'}, {'credit_id': '54491d6cc3a3680fa5001b2c', 'department': 'Sound', 'gender': 0, 'id': 8163, 'job': 'Foley', 'name': 'Jana Vance'}, {'credit_id': '52fe48009251416c750aca57', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 8527, 'job': 'Costume Design', 'name': 'Deborah Lynn Scott'}, {'credit_id': '52fe48009251416c750aca2f', 'department': 'Production', 'gender': 2, 'id': 8529, 'job': 'Producer', 'name': 'Jon Landau'}, {'credit_id': '539c4937c3a36810ba002194', 'department': 'Art', 'gender': 0, 'id': 9618, 'job': 'Art Direction', 'name': 'Sean Haworth'}, {'credit_id': '539c49b6c3a36810c10020e6', 'department': 'Art', 'gender': 1, 'id': 12653, 'job': 'Set Decoration', 'name': 'Kim Sinclair'}, {'credit_id': '570b6f2f9251413a0e00020d', 'department': 'Art', 'gender': 1, 'id': 12653, 'job': 'Supervising Art Director', 'name': 'Kim Sinclair'}, {'credit_id': '54491a6c0e0a26748c001b19', 'department': 'Art', 'gender': 2, 'id': 14350, 'job': 'Set Designer', 'name': 'Richard F. Mays'}, {'credit_id': '56928cf4c3a3684cff0025c4', 'department': 'Production', 'gender': 1, 'id': 20294, 'job': 'Executive Producer', 'name': 'Laeta Kalogridis'}, {'credit_id': '52fe48009251416c750aca51', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 17675, 'job': 'Costume Design', 'name': 'Mayes C. Rubeo'}, {'credit_id': '52fe48009251416c750aca11', 'department': 'Camera', 'gender': 2, 'id': 18265, 'job': 'Director of Photography', 'name': 'Mauro Fiore'}, {'credit_id': '5449194d0e0a26748f001b39', 'department': 'Art', 'gender': 0, 'id': 42281, 'job': 'Set Designer', 'name': 'Scott Herbertson'}, {'credit_id': '52fe48009251416c750aca05', 'department': 'Crew', 'gender': 0, 'id': 42288, 'job': 'Stunts', 'name': 'Woody Schultz'}, {'credit_id': '5592aefb92514152de0010f5', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 29067, 'job': 'Makeup Artist', 'name': 'Linda DeVetta'}, {'credit_id': '5592afa492514152de00112c', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 29067, 'job': 'Hairstylist', 'name': 'Linda DeVetta'}, {'credit_id': '54959ed592514130fc002e5d', 'department': 'Camera', 'gender': 2, 'id': 33302, 'job': 'Camera Operator', 'name': 'Richard Bluck'}, {'credit_id': '539c4891c3a36810ba002147', 'department': 'Art', 'gender': 2, 'id': 33303, 'job': 'Art Direction', 'name': 'Simon Bright'}, {'credit_id': '54959c069251417a81001f3a', 'department': 'Visual Effects', 'gender': 0, 'id': 113145, 'job': 'Visual Effects Supervisor', 'name': 'Richard Martin'}, {'credit_id': '54959a0dc3a3680ff5002c8d', 'department': 'Crew', 'gender': 2, 'id': 58188, 'job': 'Visual Effects Editor', 'name': 'Steve R. Moore'}, {'credit_id': '52fe48009251416c750aca1d', 'department': 'Editing', 'gender': 2, 'id': 58871, 'job': 'Editor', 'name': 'John Refoua'}, {'credit_id': '54491a4dc3a3680fc30018ca', 'department': 'Art', 'gender': 0, 'id': 92359, 'job': 'Set Designer', 'name': 'Karl J. Martin'}, {'credit_id': '52fe48009251416c750aca35', 'department': 'Camera', 'gender': 1, 'id': 72201, 'job': 'Director of Photography', 'name': 'Chiling Lin'}, {'credit_id': '52fe48009251416c750ac9ff', 'department': 'Crew', 'gender': 0, 'id': 89714, 'job': 'Stunts', 'name': 'Ilram Choi'}, {'credit_id': '54959c529251416e2b004394', 'department': 'Visual Effects', 'gender': 2, 'id': 93214, 'job': 'Visual Effects Supervisor', 'name': 'Steven Quale'}, {'credit_id': '54491edf0e0a267489001c37', 'department': 'Crew', 'gender': 1, 'id': 122607, 'job': 'Dialect Coach', 'name': 'Carla Meyer'}, {'credit_id': '539c485bc3a368653d001a3a', 'department': 'Art', 'gender': 2, 'id': 132585, 'job': 'Art Direction', 'name': 'Nick Bassett'}, {'credit_id': '539c4903c3a368653d001a74', 'department': 'Art', 'gender': 0, 'id': 132596, 'job': 'Art Direction', 'name': 'Jill Cormack'}, {'credit_id': '539c4967c3a368653d001a94', 'department': 'Art', 'gender': 0, 'id': 132604, 'job': 'Art Direction', 'name': 'Andy McLaren'}, {'credit_id': '52fe48009251416c750aca45', 'department': 'Crew', 'gender': 0, 'id': 236696, 'job': 'Motion Capture Artist', 'name': 'Terry Notary'}, {'credit_id': '54959e02c3a3680fc60027d2', 'department': 'Crew', 'gender': 2, 'id': 956198, 'job': 'Stunt Coordinator', 'name': 'Garrett Warren'}, {'credit_id': '54959ca3c3a3686ae300438c', 'department': 'Visual Effects', 'gender': 2, 'id': 957874, 'job': 'Visual Effects Supervisor', 'name': 'Jonathan Rothbart'}, {'credit_id': '570b6f519251412c74001b2f', 'department': 'Art', 'gender': 0, 'id': 957889, 'job': 'Supervising Art Director', 'name': 'Stefan Dechant'}, {'credit_id': '570b6f62c3a3680b77007460', 'department': 'Art', 'gender': 2, 'id': 959555, 'job': 'Supervising Art Director', 'name': 'Todd Cherniawsky'}, {'credit_id': '539c4a3ac3a36810da0021cc', 'department': 'Production', 'gender': 0, 'id': 1016177, 'job': 'Casting', 'name': 'Miranda Rivers'}, {'credit_id': '539c482cc3a36810c1002062', 'department': 'Art', 'gender': 0, 'id': 1032536, 'job': 'Production Design', 'name': 'Robert Stromberg'}, {'credit_id': '539c4b65c3a36810c9002125', 'department': 'Costume & Make-Up', 'gender': 2, 'id': 1071680, 'job': 'Costume Design', 'name': 'John Harding'}, {'credit_id': '54959e6692514130fc002e4e', 'department': 'Camera', 'gender': 0, 'id': 1177364, 'job': 'Steadicam Operator', 'name': 'Roberto De Angelis'}, {'credit_id': '539c49f1c3a368653d001aac', 'department': 'Costume & Make-Up', 'gender': 2, 'id': 1202850, 'job': 'Makeup Department Head', 'name': 'Mike Smithson'}, {'credit_id': '5495999ec3a3686ae100460c', 'department': 'Visual Effects', 'gender': 0, 'id': 1204668, 'job': 'Visual Effects Producer', 'name': 'Alain Lalanne'}, {'credit_id': '54959cdfc3a3681153002729', 'department': 'Visual Effects', 'gender': 0, 'id': 1206410, 'job': 'Visual Effects Supervisor', 'name': 'Lucas Salton'}, {'credit_id': '549596239251417a81001eae', 'department': 'Crew', 'gender': 0, 'id': 1234266, 'job': 'Post Production Supervisor', 'name': 'Janace Tashjian'}, {'credit_id': '54959c859251416e1e003efe', 'department': 'Visual Effects', 'gender': 0, 'id': 1271932, 'job': 'Visual Effects Supervisor', 'name': 'Stephen Rosenbaum'}, {'credit_id': '5592af28c3a368775a00105f', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1310064, 'job': 'Makeup Artist', 'name': 'Frankie Karena'}, {'credit_id': '539c4adfc3a36810e300203b', 'department': 'Costume & Make-Up', 'gender': 1, 'id': 1319844, 'job': 'Costume Supervisor', 'name': 'Lisa Lovaas'}, {'credit_id': '54959b579251416e2b004371', 'department': 'Visual Effects', 'gender': 0, 'id': 1327028, 'job': 'Visual Effects Supervisor', 'name': 'Jonathan Fawkner'}, {'credit_id': '539c48a7c3a36810b5001fa7', 'department': 'Art', 'gender': 0, 'id': 1330561, 'job': 'Art Direction', 'name': 'Robert Bavin'}, {'credit_id': '539c4a71c3a36810da0021e0', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330567, 'job': 'Costume Supervisor', 'name': 'Anthony Almaraz'}, {'credit_id': '539c4a8ac3a36810ba0021e4', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330570, 'job': 'Costume Supervisor', 'name': 'Carolyn M. Fenton'}, {'credit_id': '539c4ab6c3a36810da0021f0', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1330574, 'job': 'Costume Supervisor', 'name': 'Beth Koenigsberg'}, {'credit_id': '54491ab70e0a267480001ba2', 'department': 'Art', 'gender': 0, 'id': 1336191, 'job': 'Set Designer', 'name': 'Sam Page'}, {'credit_id': '544919d9c3a3680fc30018bd', 'department': 'Art', 'gender': 0, 'id': 1339441, 'job': 'Set Designer', 'name': 'Tex Kadonaga'}, {'credit_id': '54491cf50e0a267483001b0c', 'department': 'Editing', 'gender': 0, 'id': 1352422, 'job': 'Dialogue Editor', 'name': 'Kim Foscato'}, {'credit_id': '544919f40e0a26748c001b09', 'department': 'Art', 'gender': 0, 'id': 1352962, 'job': 'Set Designer', 'name': 'Tammy S. Lee'}, {'credit_id': '5495a115c3a3680ff5002d71', 'department': 'Crew', 'gender': 0, 'id': 1357070, 'job': 'Transportation Coordinator', 'name': 'Denny Caira'}, {'credit_id': '5495a12f92514130fc002e94', 'department': 'Crew', 'gender': 0, 'id': 1357071, 'job': 'Transportation Coordinator', 'name': 'James Waitkus'}, {'credit_id': '5495976fc3a36811530026b0', 'department': 'Sound', 'gender': 0, 'id': 1360103, 'job': 'Supervising Sound Editor', 'name': 'Addison Teague'}, {'credit_id': '54491837c3a3680fb1001c5a', 'department': 'Art', 'gender': 2, 'id': 1376887, 'job': 'Set Designer', 'name': 'C. Scott Baker'}, {'credit_id': '54491878c3a3680fb4001c9d', 'department': 'Art', 'gender': 0, 'id': 1376888, 'job': 'Set Designer', 'name': 'Luke Caska'}, {'credit_id': '544918dac3a3680fa5001ae0', 'department': 'Art', 'gender': 0, 'id': 1376889, 'job': 'Set Designer', 'name': 'David Chow'}, {'credit_id': '544919110e0a267486001b68', 'department': 'Art', 'gender': 0, 'id': 1376890, 'job': 'Set Designer', 'name': 'Jonathan Dyer'}, {'credit_id': '54491967c3a3680faa001b5e', 'department': 'Art', 'gender': 0, 'id': 1376891, 'job': 'Set Designer', 'name': 'Joseph Hiura'}, {'credit_id': '54491997c3a3680fb1001c8a', 'department': 'Art', 'gender': 0, 'id': 1376892, 'job': 'Art Department Coordinator', 'name': 'Rebecca Jellie'}, {'credit_id': '544919ba0e0a26748f001b42', 'department': 'Art', 'gender': 0, 'id': 1376893, 'job': 'Set Designer', 'name': 'Robert Andrew Johnson'}, {'credit_id': '54491b1dc3a3680faa001b8c', 'department': 'Art', 'gender': 0, 'id': 1376895, 'job': 'Assistant Art Director', 'name': 'Mike Stassi'}, {'credit_id': '54491b79c3a3680fbb001826', 'department': 'Art', 'gender': 0, 'id': 1376897, 'job': 'Construction Coordinator', 'name': 'John Villarino'}, {'credit_id': '54491baec3a3680fb4001ce6', 'department': 'Art', 'gender': 2, 'id': 1376898, 'job': 'Assistant Art Director', 'name': 'Jeffrey Wisniewski'}, {'credit_id': '54491d2fc3a3680fb4001d07', 'department': 'Editing', 'gender': 0, 'id': 1376899, 'job': 'Dialogue Editor', 'name': 'Cheryl Nardi'}, {'credit_id': '54491d86c3a3680fa5001b2f', 'department': 'Editing', 'gender': 0, 'id': 1376901, 'job': 'Dialogue Editor', 'name': 'Marshall Winn'}, {'credit_id': '54491d9dc3a3680faa001bb0', 'department': 'Sound', 'gender': 0, 'id': 1376902, 'job': 'Supervising Sound Editor', 'name': 'Gwendolyn Yates Whittle'}, {'credit_id': '54491dc10e0a267486001bce', 'department': 'Sound', 'gender': 0, 'id': 1376903, 'job': 'Sound Re-Recording Mixer', 'name': 'William Stein'}, {'credit_id': '54491f500e0a26747c001c07', 'department': 'Crew', 'gender': 0, 'id': 1376909, 'job': 'Choreographer', 'name': 'Lula Washington'}, {'credit_id': '549599239251412c4e002a2e', 'department': 'Visual Effects', 'gender': 0, 'id': 1391692, 'job': 'Visual Effects Producer', 'name': 'Chris Del Conte'}, {'credit_id': '54959d54c3a36831b8001d9a', 'department': 'Visual Effects', 'gender': 2, 'id': 1391695, 'job': 'Visual Effects Supervisor', 'name': 'R. Christopher White'}, {'credit_id': '54959bdf9251412c4e002a66', 'department': 'Visual Effects', 'gender': 0, 'id': 1394070, 'job': 'Visual Effects Supervisor', 'name': 'Dan Lemmon'}, {'credit_id': '5495971d92514132ed002922', 'department': 'Sound', 'gender': 0, 'id': 1394129, 'job': 'Sound Effects Editor', 'name': 'Tim Nielsen'}, {'credit_id': '5592b25792514152cc0011aa', 'department': 'Crew', 'gender': 0, 'id': 1394286, 'job': 'CG Supervisor', 'name': 'Michael Mulholland'}, {'credit_id': '54959a329251416e2b004355', 'department': 'Crew', 'gender': 0, 'id': 1394750, 'job': 'Visual Effects Editor', 'name': 'Thomas Nittmann'}, {'credit_id': '54959d6dc3a3686ae9004401', 'department': 'Visual Effects', 'gender': 0, 'id': 1394755, 'job': 'Visual Effects Supervisor', 'name': 'Edson Williams'}, {'credit_id': '5495a08fc3a3686ae300441c', 'department': 'Editing', 'gender': 0, 'id': 1394953, 'job': 'Digital Intermediate', 'name': 'Christine Carr'}, {'credit_id': '55402d659251413d6d000249', 'department': 'Visual Effects', 'gender': 0, 'id': 1395269, 'job': 'Visual Effects Supervisor', 'name': 'John Bruno'}, {'credit_id': '54959e7b9251416e1e003f3e', 'department': 'Camera', 'gender': 0, 'id': 1398970, 'job': 'Steadicam Operator', 'name': 'David Emmerichs'}, {'credit_id': '54959734c3a3686ae10045e0', 'department': 'Sound', 'gender': 0, 'id': 1400906, 'job': 'Sound Effects Editor', 'name': 'Christopher Scarabosio'}, {'credit_id': '549595dd92514130fc002d79', 'department': 'Production', 'gender': 0, 'id': 1401784, 'job': 'Production Supervisor', 'name': 'Jennifer Teves'}, {'credit_id': '549596009251413af70028cc', 'department': 'Production', 'gender': 0, 'id': 1401785, 'job': 'Production Manager', 'name': 'Brigitte Yorke'}, {'credit_id': '549596e892514130fc002d99', 'department': 'Sound', 'gender': 0, 'id': 1401786, 'job': 'Sound Effects Editor', 'name': 'Ken Fischer'}, {'credit_id': '549598229251412c4e002a1c', 'department': 'Crew', 'gender': 0, 'id': 1401787, 'job': 'Special Effects Coordinator', 'name': 'Iain Hutton'}, {'credit_id': '549598349251416e2b00432b', 'department': 'Crew', 'gender': 0, 'id': 1401788, 'job': 'Special Effects Coordinator', 'name': 'Steve Ingram'}, {'credit_id': '54959905c3a3686ae3004324', 'department': 'Visual Effects', 'gender': 0, 'id': 1401789, 'job': 'Visual Effects Producer', 'name': 'Joyce Cox'}, {'credit_id': '5495994b92514132ed002951', 'department': 'Visual Effects', 'gender': 0, 'id': 1401790, 'job': 'Visual Effects Producer', 'name': 'Jenny Foster'}, {'credit_id': '549599cbc3a3686ae1004613', 'department': 'Crew', 'gender': 0, 'id': 1401791, 'job': 'Visual Effects Editor', 'name': 'Christopher Marino'}, {'credit_id': '549599f2c3a3686ae100461e', 'department': 'Crew', 'gender': 0, 'id': 1401792, 'job': 'Visual Effects Editor', 'name': 'Jim Milton'}, {'credit_id': '54959a51c3a3686af3003eb5', 'department': 'Visual Effects', 'gender': 0, 'id': 1401793, 'job': 'Visual Effects Producer', 'name': 'Cyndi Ochs'}, {'credit_id': '54959a7cc3a36811530026f4', 'department': 'Crew', 'gender': 0, 'id': 1401794, 'job': 'Visual Effects Editor', 'name': 'Lucas Putnam'}, {'credit_id': '54959b91c3a3680ff5002cb4', 'department': 'Visual Effects', 'gender': 0, 'id': 1401795, 'job': 'Visual Effects Supervisor', 'name': "Anthony 'Max' Ivins"}, {'credit_id': '54959bb69251412c4e002a5f', 'department': 'Visual Effects', 'gender': 0, 'id': 1401796, 'job': 'Visual Effects Supervisor', 'name': 'John Knoll'}, {'credit_id': '54959cbbc3a3686ae3004391', 'department': 'Visual Effects', 'gender': 2, 'id': 1401799, 'job': 'Visual Effects Supervisor', 'name': 'Eric Saindon'}, {'credit_id': '54959d06c3a3686ae90043f6', 'department': 'Visual Effects', 'gender': 0, 'id': 1401800, 'job': 'Visual Effects Supervisor', 'name': 'Wayne Stables'}, {'credit_id': '54959d259251416e1e003f11', 'department': 'Visual Effects', 'gender': 0, 'id': 1401801, 'job': 'Visual Effects Supervisor', 'name': 'David Stinnett'}, {'credit_id': '54959db49251413af7002975', 'department': 'Visual Effects', 'gender': 0, 'id': 1401803, 'job': 'Visual Effects Supervisor', 'name': 'Guy Williams'}, {'credit_id': '54959de4c3a3681153002750', 'department': 'Crew', 'gender': 0, 'id': 1401804, 'job': 'Stunt Coordinator', 'name': 'Stuart Thorp'}, {'credit_id': '54959ef2c3a3680fc60027f2', 'department': 'Lighting', 'gender': 0, 'id': 1401805, 'job': 'Best Boy Electric', 'name': 'Giles Coburn'}, {'credit_id': '54959f07c3a3680fc60027f9', 'department': 'Camera', 'gender': 2, 'id': 1401806, 'job': 'Still Photographer', 'name': 'Mark Fellman'}, {'credit_id': '54959f47c3a3681153002774', 'department': 'Lighting', 'gender': 0, 'id': 1401807, 'job': 'Lighting Technician', 'name': 'Scott Sprague'}, {'credit_id': '54959f8cc3a36831b8001df2', 'department': 'Visual Effects', 'gender': 0, 'id': 1401808, 'job': 'Animation Director', 'name': 'Jeremy Hollobon'}, {'credit_id': '54959fa0c3a36831b8001dfb', 'department': 'Visual Effects', 'gender': 0, 'id': 1401809, 'job': 'Animation Director', 'name': 'Orlando Meunier'}, {'credit_id': '54959fb6c3a3686af3003f54', 'department': 'Visual Effects', 'gender': 0, 'id': 1401810, 'job': 'Animation Director', 'name': 'Taisuke Tanimura'}, {'credit_id': '54959fd2c3a36831b8001e02', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1401812, 'job': 'Set Costumer', 'name': 'Lilia Mishel Acevedo'}, {'credit_id': '54959ff9c3a3686ae300440c', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 1401814, 'job': 'Set Costumer', 'name': 'Alejandro M. Hernandez'}, {'credit_id': '5495a0ddc3a3686ae10046fe', 'department': 'Editing', 'gender': 0, 'id': 1401815, 'job': 'Digital Intermediate', 'name': 'Marvin Hall'}, {'credit_id': '5495a1f7c3a3686ae3004443', 'department': 'Production', 'gender': 0, 'id': 1401816, 'job': 'Publicist', 'name': 'Judy Alley'}, {'credit_id': '5592b29fc3a36869d100002f', 'department': 'Crew', 'gender': 0, 'id': 1418381, 'job': 'CG Supervisor', 'name': 'Mike Perry'}, {'credit_id': '5592b23a9251415df8001081', 'department': 'Crew', 'gender': 0, 'id': 1426854, 'job': 'CG Supervisor', 'name': 'Andrew Morley'}, {'credit_id': '55491e1192514104c40002d8', 'department': 'Art', 'gender': 0, 'id': 1438901, 'job': 'Conceptual Design', 'name': 'Seth Engstrom'}, {'credit_id': '5525d5809251417276002b06', 'department': 'Crew', 'gender': 0, 'id': 1447362, 'job': 'Visual Effects Art Director', 'name': 'Eric Oliver'}, {'credit_id': '554427ca925141586500312a', 'department': 'Visual Effects', 'gender': 0, 'id': 1447503, 'job': 'Modeling', 'name': 'Matsune Suzuki'}, {'credit_id': '551906889251415aab001c88', 'department': 'Art', 'gender': 0, 'id': 1447524, 'job': 'Art Department Manager', 'name': 'Paul Tobin'}, {'credit_id': '5592af8492514152cc0010de', 'department': 'Co

In [158]:
director=movies['crew'].apply(
    lambda x:[i['name'].replace(' ','_')
    for i in x if i['job']=='Director']
    if isinstance(x,list) else [])
director=director.apply(lambda x:x[0] if len(x)>0 else "")

In [162]:
print(director[director.apply(lambda x:isinstance(x,str))].sum())
movies['director']=director.apply(lambda x:[x])

James_CameronGore_VerbinskiSam_MendesChristopher_NolanAndrew_StantonSam_RaimiByron_HowardJoss_WhedonDavid_YatesZack_SnyderBryan_SingerMarc_ForsterGore_VerbinskiGore_VerbinskiZack_SnyderAndrew_AdamsonJoss_WhedonRob_MarshallBarry_SonnenfeldPeter_JacksonMarc_WebbRidley_ScottPeter_JacksonChris_WeitzPeter_JacksonJames_CameronAnthony_RussoPeter_BergColin_TrevorrowSam_MendesSam_RaimiShane_BlackTim_BurtonBrett_RatnerDan_ScanlonMichael_BayMichael_BaySam_RaimiMarc_WebbJoseph_KosinskiJohn_LasseterMartin_CampbellLee_UnkrichMcGJames_WanMarc_ForsterBryan_SingerJ.J._AbramsBryan_SingerBaz_LuhrmannMike_NewellGuillermo_del_ToroMichael_BaySteven_SpielbergPeter_SohnBrenda_ChapmanJustin_LinAndrew_StantonBrett_RatnerRoland_EmmerichRobert_ZemeckisLilly_WachowskiDavid_YatesAndrew_AdamsonBryan_SingerChristopher_NolanPete_DocterConrad_VernonJon_FavreauMartin_ScorseseBarry_SonnenfeldRob_CohenDavid_AyerTom_ShadyacDoug_LimanKevin_ReynoldsStephen_SommersPete_DocterJon_FavreauJon_FavreauRupert_SandersRobert_StrombergMatt_ReevesRoland_JofféCarl_RinschAnthony_RussoMike_MitchellBrad_BirdChris_WilliamsRich_MooreRobert_ZemeckisRoland_EmmerichChris_SandersJonathan_MostowJames_GunnChristopher_NolanChristopher_NolanHideaki_AnnoPeter_JacksonRob_CohenDavid_FincherMatthew_VaughnFrancis_LawrenceJon_TurteltaubWolfgang_PetersenJames_BobinChris_MillerDuncan_JonesAlan_TaylorMichael_AptedMichael_BayMichael_BayOliver_StoneDavid_YatesMike_NewellPeter_BergFrancis_LawrenceTim_BurtonJan_PinkavaChristopher_NolanEric_DarnellShawn_LevyGavin_HoodLilly_WachowskiChris_BuckLilly_WachowskiAlan_TaylorGeorge_MillerRon_HowardKenneth_BranaghChris_WilliamsHoyt_YeatmanJonathan_LiebesmanTim_BurtonChristopher_McQuarrieJoe_JohnstonSteve_HicknerJennifer_Yuh_NelsonM._Night_ShyamalanJ.J._AbramsRoland_EmmerichSimon_WellsDavid_BowersJoe_WrightRob_MinkoffWolfgang_PetersenConrad_VernonLee_TamahoriPaul_FeigMichael_BayBarry_SonnenfeldRobert_ZemeckisJennifer_Yuh_NelsonBrad_BirdPeter_RamseyDean_ParisotEdward_ZwickRidley_ScottJ.J._AbramsSam_RaimiDean_DeBloisAlex_ProyasRob_CohenZack_SnyderRichard_DonnerAng_LeeJon_M._ChuBreck_EisnerHironobu_SakaguchiJoe_JohnstonMichael_AptedPeter_WeirBill_CondonGeorge_MillerLouis_LeterrierSteven_SpielbergAlejandro_González_IñárrituDavid_SorenGore_VerbinskiEric_DarnellPaul_GreengrassMark_OsbornePeyton_ReedFrancis_LawrenceTim_JohnsonSteven_SpielbergMichael_BayChris_MillerPhillip_NoyceDarren_AronofskySteven_SpielbergAlfonso_CuarónBaz_LuhrmannM._Night_ShyamalanRalph_ZondagShawn_LevyTom_McGrathChris_ColumbusRobert_SchwentkeGore_VerbinskiFrancis_LawrenceRon_HowardCarlos_SaldanhaBryan_SingerJustin_LinGuy_RitchieLouis_LeterrierPaul_VerhoevenJohn_McTiernanTony_GilroyJoel_SchumacherRon_HowardRoland_EmmerichJohn_WooWolfgang_PetersenTim_StoryAng_LeeMark_Steven_JohnsonPaul_GreengrassMcGRidley_ScottRob_MinkoffNeill_BlomkampDavid_TwohyJosé_PadilhaLilly_WachowskiJames_L._BrooksJames_MangoldJoseph_KosinskiGeorge_LucasGeorge_LucasPete_DocterJames_MangoldGeorge_LucasChris_SandersThomas_LangmannJohn_WooCedric_Nicolas-TroyanJonathan_LiebesmanAlfonso_CuarónRoger_DonaldsonDave_GreenJosh_TrankShawn_LevyBrad_PeytonRoger_SpottiswoodeRoland_EmmerichSteven_SoderberghDoug_LimanRobert_SchwentkeMartin_ScorseseRob_LettermanMichel_GondryNoam_MurroRaja_GosnellWill_FinnRobert_SchwentkeShawn_LevyRaja_GosnellJan_de_BontGavin_HoodLen_WisemanPeter_JacksonFrank_CoraciMichael_MannBo_WelchAlex_ProyasRidley_ScottRob_MinkoffRon_ClementsRidley_ScottMichael_BayPeter_ChelsomDominic_SenaRidley_ScottSteven_SpielbergChris_ColumbusMartin_CampbellTim_BurtonJames_CameronMichael_MannRidley_ScottJames_CameronTony_ScottPaul_WeitzAdam_McKayChuck_RussellQuentin_TarantinoGary_TrousdaleMark_DindalSimon_WestJon_TurteltaubStefen_FangmeierSpike_JonzeChris_WedgeFlorian_Henckel_von_DonnersmarckPeter_HyamsEdward_ZwickMartin_ScorseseJoel_SchumacherPaul_VerhoevenTom_TykwerZack_SnyderPitofBrett_RatnerRon_ClementsBrad_SilberlingPatrick_HughesEricson_CoreLawrence_GutermanRon_HowardRon_UnderwoodPaul_GreengrassSteve_MartinoDavid_MametStephen_SommersMartin_ScorseseZhang_YimouAsh_BrannonFrank_OzRidley_ScottJay_RoachLuc_BessonMichael_Patrick_KingDon_Michael_PaulSteve_MartinoKenneth_BranaghPeter_JacksonAndrew_StantonPeter_JacksonPeter_JacksonSergei_BodrovSimon_WestWally_PfisterJoe_JohnstonRupert_WyattMark_WatersJohn_MooreJohn_Lee_HancockBrad_BirdRenny_HarlinChris_ColumbusBarry_SonnenfeldJohn_LasseterTony_ScottBrett_RatnerRobert_ZemeckisPhil_LordCarlos_SaldanhaBen_StillerMcGMartin_ScorseseTony_BancroftBen_StillerDavid_FincherJohn_McTiernanGuy_RitchieTimur_BekmambetovGary_TrousdaleWalt_BeckerBryan_SingerDennis_DuganChris_ColumbusSteven_SpielbergRob_MinkoffRobert_ZemeckisPaul_VerhoevenSydney_PollackThor_FreudenthalJan_de_BontJon_M._ChuPhillip_NoyceTony_ScottBrian_De_PalmaCarlos_SaldanhaChris_ColumbusMick_JacksonAlan_J._PakulaKathryn_BigelowJohn_MiliusRon_HowardAndrei_KonchalovskyGary_RossJan_de_BontRobert_ZemeckisGeorge_MillerPaul_GreengrassWolfgang_PetersenSteven_SoderberghPaul_W.S._AndersonGenndy_TartakovskyKevin_LimaDaniel_EspinosaKevin_LimaBrett_RatnerNancy_MeyersTony_ScottNancy_MeyersSteven_SoderberghJill_CultonNeil_BurgerJean-Jacques_AnnaudPeter_BergJohn_McTiernanRob_MarshallJustin_LinBarry_CookMartin_BrestAndrew_DavisBob_FosseTarsem_SinghEdgar_WrightJon_AmielPeter_SegalRaja_GosnellPete_TravisFrank_CoraciGeorge_A._RomeroBrad_PeytonDoug_LimanGuillermo_del_ToroDavid_FincherRoger_SpottiswoodeTom_ShadyacSylvester_StalloneBrian_De_PalmaGary_RossTodd_PhillipsTim_BurtonKarey_KirkpatrickChris_SandersGary_WinickMimi_LederDean_ParisotPeter_SegalMike_MitchellDennis_DuganPeter_SegalNancy_MeyersMartin_ScorseseSeth_GordonChris_WedgeJohn_WooAdam_ShankmanSam_MendesDennis_DuganSimon_WestD.J._CarusoAnthony_MinghellaAlbert_HughesLes_MayfieldJan_de_BontJoe_PytkaShawn_LevyScott_DerricksonRichard_DonnerDavid_AyerIvan_ReitmanEric_BrevigKelly_AsburyFrank_CoraciStephen_HopkinsJonathan_DemmeHenry_JaglomGenndy_TartakovskyJames_AlgarSimon_WellsRon_UnderwoodDominic_SenaMartin_CampbellVincent_WardSteven_BrillTerry_GilliamTim_BurtonLucile_HadzihalilovicLee_TamahoriJonathan_MostowRoger_DonaldsonRob_CohenBarry_CookRoger_ChristianJoe_DanteRob_MarshallRichard_DonnerKevin_CostnerGeorge_MillerBreck_EisnerAntony_HoffmanLuc_BessonJacques_PerrinPeter_HyamsPaul_W.S._AndersonAndrés_CouturierRon_HowardRoger_AllersBrad_PeytonCody_CameronBrett_RatnerJoe_JohnstonDennis_DuganJohn_SingletonMark_OsborneOliver_HirschbiegelDes_McAnuffChris_RenaudStephen_NorringtonPierre_CoffinRoland_EmmerichSteven_SpielbergEric_DarnellAlfonso_CuarónBryan_SingerTimur_BekmambetovMichael_BayCarlos_SaldanhaPeter_SegalAdam_ShankmanRenny_HarlinDavid_KelloggLouis_LeterrierDennis_DuganSteven_SpielbergThor_FreudenthalMartin_CampbellMike_NicholsVicky_JensonBill_CondonF._Gary_GraySteven_SpielbergAntoine_FuquaRobert_LuketicGuy_RitchieJames_L._BrooksGil_KenanBarry_LevinsonJerry_ZuckerAndy_TennantTarsem_SinghFlorent-Emilio_SiriGary_GoldmanRon_SheltonPaul_W.S._AndersonÀlex_PastorHenry_SelickJohn_MooreM._Night_ShyamalanKyle_BaldaZack_SnyderBrian_De_PalmaBarry_LevinsonFergal_ReillyAndy_TennantJudd_ApatowPeter_BergAdam_McKaySteve_CarrMel_GibsonSam_MendesDavid_SilvermanFrank_DarabontRenny_HarlinJean-Jacques_AnnaudM._Night_ShyamalanBetty_ThomasM._Night_ShyamalanAndrew_AdamsonJohn_LasseterGarry_MarshallRob_CohenPaul_TibbittRon_HowardQuentin_TarantinoSteven_SpielbergRenny_HarlinClark_JohnsonCameron_CroweM._Night_ShyamalanPaul_W.S._AndersonBetty_ThomasRandall_WallaceAntoine_FuquaJonathan_FrakesJonathan_LiebesmanTim_BurtonMike_NicholsSteven_SpielbergGeorge_ClooneyJames_CameronOliver_StoneGary_ShoreEdward_ZwickMatthew_VaughnJean-Jacques_AnnaudRon_HowardJoel_SchumacherAndrzej_BartkowiakBetty_ThomasMåns_MårlindAdam_ShankmanGregory_HoblitGary_McKendryJohn_McTiernanWych_KaosayanandaMikael_SalomonBobby_FarrellyDan_St._PierreMichael_MannKerry_ConranMichael_Caton-JonesMikael_HåfströmRenny_HarlinPhil_Alden_RobinsonDavid_SladeFrank_OzPierre_CoffinJoseph_RubenSeth_MacFarlaneAlejandro_AmenábarKinka_UsherBobby_FarrellyMichael_MannCraig_GillespieRidley_ScottJay_RoachTimur_BekmambetovJon_AmielRob_BowmanDoug_LeflerSteven_SpielbergScott_WaughNancy_MeyersChris_WedgeLawrence_KasdanSteven_SpielbergLilly_WachowskiRon_HowardMichael_LembeckTom_HooperNora_EphronAdam_McKayMartin_CampbellTodd_PhillipsAngelina_JolieClint_EastwoodRenny_HarlinJohn_WooJon_TurteltaubOliver_StoneMike_NewellLarry_CharlesStanley_KubrickWill_GluckGlenn_FicarraMcGDavid_S._GoyerJohn_MiliusMike_NicholsPaul_W.S._AndersonPaul_W.S._AndersonRenny_HarlinTaylor_HackfordJon_FavreauDavid_FincherMcGMichael_LehmannNora_EphronStuart_BeattieRoman_PolanskiRob_BowmanRobert_RodriguezSydney_PollackBaltasar_KormákurTom_TykwerJay_RoachDavid_BowersSteven_SpielbergLawrence_KasdanPhillip_NoyceDaniel_LeeKeenen_Ivory_WayansJonathan_MostowRob_ReinerMarco_SchnabelDemian_LichtensteinQuentin_TarantinoJosh_GordonTim_HillZack_SnyderJay_RoachDavid_FrankelFrank_DarabontWalt_BeckerMark_DindalDavid_FincherDoug_LimanMartin_CampbellSimon_WestPeter_WeirSimon_WellsSteve_CarrBaltasar_KormákurLawrence_GutermanF._Gary_GrayMarc_LawrenceEric_DarnellPeter_BillingsleyTony_ScottAdam_ShankmanWes_BallRyan_MurphyBrett_RatnerRobert_SchwentkeOliver_StoneRobert_RedfordMichael_MannChuck_RussellJay_RussellChristopher_McQuarrieRenny_HarlinKenny_OrtegaSteven_SoderberghDavid_McNallyHenry_SelickM._Night_ShyamalanTony_ScottBrian_RobbinsTodd_PhillipsBrian_LevantGuillermo_del_ToroSteven_ZaillianSam_FellMichael_Caton-JonesJohn_WooJon_AvnetRobert_StevenhagenKevin_DonovanGeoff_MurphyKenneth_BranaghDavid_O._RussellBabak_NajafiJean-Pierre_JeunetAntoine_FuquaAnthony_StacchiGriffin_DunnePhil_LordJohn_PasquinRob_BowmanRuben_FleischerHarold_RamisClint_EastwoodKevin_MacdonaldTony_GilroyDonald_PetrieClark_JohnsonJorge_BlancoStuart_BairdJoel_CoenRobert_LorenzMartin_CampbellPeter_HyamsHarold_RamisJon_AvnetHarold_BeckerJoe_WrightRobert_RedfordCameron_CroweTim_HillLee_TamahoriScott_StewartTim_JohnsonPaul_W.S._AndersonTom_ShadyacBrian_De_PalmaTony_BillRod_LurieWalter_HillAkiva_GoldsmanHarald_ZwartBrian_RobbinsWalter_SallesRon_HowardIain_SoftleyFrank_MillerDavid_KoeppUwe_BollMartin_CampbellSoi_CheangJohn_DahlTim_MillerStephen_HerekClint_EastwoodRob_LettermanMark_WatersBrian_LevantPeter_MacDonaldGeorge_ClooneyFrank_CoraciMarc_LawrenceShawn_LevyPaul_W.S._AndersonAnthony_HemingwayTaylor_HackfordSean_AndersRob_CohenBrett_RatnerBrian_TaylorJohn_MaddenAdam_ShankmanKevin_BrayRobert_ZemeckisTim_HillJay_RoachMike_GabrielRichard_DonnerTom_ShadyacAndy_TennantSam_WeismanJesse_DylanPaul_GreengrassShawn_LevyBrad_SilberlingAntoine_FuquaWayne_WangTony_ScottGabriele_MuccinoRobert_SchwentkeBarry_LevinsonBrad_SilberlingQuentin_TarantinoFrank_OzQuentin_TarantinoAndrei_KonchalovskyRobert_ZemeckisTom_DeyStuart_BairdMark_WatersRob_MinkoffJimmy_HaywardDavid_FincherAlan_ParkerJohn_FrankenheimerStephen_HopkinsPaul_KingAkiva_SchafferWilliam_FriedkinJon_TurteltaubBobby_FarrellyKent_AltermanPeter_LordClint_EastwoodAndrew_DavisTony_ScottJoel_SchumacherShekhar_KapurKaryn_KusamaRonald_F._MaxwellRobert_ButlerKarey_KirkpatrickJames_BobinJonathan_FrakesSteve_AntinJean-Pierre_JeunetStanley_KubrickJim_GillespieGuillermo_del_ToroGabriele_MuccinoWalter_HillFrancis_Ford_CoppolaCameron_CroweAnthony_RussoRichard_LesterMartin_BrestSteven_ZaillianJohn_SingletonGary_GoldmanBaz_LuhrmannHarold_BeckerScott_CooperClint_EastwoodF._Gary_GrayRobert_RodriguezJonathan_DemmeCurtis_HansonSteven_SpielbergKathryn_BigelowPeyton_ReedPhyllida_LloydGarry_MarshallJay_ChandrasekharTerrence_MalickDavid_DobkinMiloš_FormanMartin_ScorsesePierre_MorelPaul_HunterBobby_FarrellySteve_OedekerkJohn_WhitesellChris_WeitzAndrew_AdamsonGeorge_NolfiKevin_ReynoldsCameron_CroweSeth_MacFarlaneJames_L._BrooksTom_ShadyacAdam_McKaySteven_BrillJ.J._AbramsSteven_SoderberghDonald_PetriePhil_LordNeil_JordanPeyton_ReedRawson_Marshall_ThurberChris_ColumbusSean_AndersRob_MarshallSpike_LeeBrian_HelgelandFrank_MarshallCameron_CroweAlex_ProyasTom_DeyHideo_NakataGlenn_FicarraPeter_HewittJoe_RothBennett_MillerWolfgang_PetersenJaume_Collet-SerraAndy_FickmanJames_McTeigueDavid_DobkinMatthew_O'CallaghanAngela_RobinsonGary_FlederTommy_WirkolaAdrian_LyneD.J._CarusoStephen_GaghanMichael_BayJorge_R._GutierrezRichard_LoncraineClint_EastwoodRidley_ScottDavid_FincherChristophe_GansHoward_DeutchJon_HurwitzF._Gary_GraySteven_QualeJohn_LandisJoe_DanteDavid_DobkinMimi_LederAlexander_WittBeeban_KidronCarl_FranklinSteven_SeagalRobert_RodriguezDanny_BoyleGarry_MarshallJames_McTeigueSam_RaimiAndrew_BergmanTom_DeyClint_EastwoodBarbet_SchroederRichard_DonnerPeter_WebberRob_ReinerAndrew_NiccolBong_Joon-hoJohn_McTiernanClint_EastwoodTom_TykwerJohn_CarpenterBrad_BirdWes_AndersonGary_RossAlan_ParkerStephen_HerekJaume_Collet-SerraDavid_CronenbergJohn_StockwellLuc_BessonDavid_Gordon_GreenJim_SheridanCosta-GavrasPatrick_Read_JohnsonRoland_JofféDoug_LimanTony_ScottWilliam_FriedkinBrian_TaylorRichard_LaGraveneseDanny_DeVitoBen_StillerGeorge_ArmitageMike_NicholsPatrick_LussierAndrzej_BartkowiakJames_WongRenny_HarlinRichard_CurtisSteven_SoderberghSteven_SpielbergJoe_WrightNeill_BlomkampPhillip_NoyceDavid_FincherChuck_BowmanDavid_O._RussellDaniel_EspinosaJerry_ZuckerIain_SoftleyJames_MangoldHarold_RamisFrancis_Ford_CoppolaJames_MangoldOlivier_MegatonSteven_SoderberghBen_StillerDeepa_MehtaWarren_BeattyJohn_McTiernanPenny_MarshallTed_KotcheffAndrei_TarkovskyYvette_KaplanStephen_FrearsP.J._HoganJoe_RothChristopher_NolanJonathan_FrakesJimmy_HaywardEdward_ZwickTom_ShadyacBrad_FurmanTerence_YoungBrian_LevantOlivier_MegatonDavid_ZuckerDonald_PetrieEric_BrevigGarry_MarshallAlan_J._PakulaJoel_SchumacherRob_ReinerPhillip_NoyceRobert_LuketicDenis_VilleneuveAntoine_FuquaDean_ParisotKeenen_Ivory_WayansJames_BobinStephen_NorringtonThomas_CarterRoger_MichellLuis_LlosaDavid_McNallyRichard_CurtisAndrew_StantonAlbert_HughesLuis_LlosaRon_SheltonMelville_ShavelsonJesse_DylanGarth_JenningsJoel_ZwickRussell_MulcahyFrank_CoraciWayne_WangCurtis_HansonFrank_OzOliver_StoneDavid_R._EllisPeter_HowittJohn_A._DavisDavid_LynchJulie_TaymorSam_MendesRichard_DonnerMathieu_KassovitzJohn_GrayHarold_RamisJohn_SchultzSean_PennSusan_StromanSimon_WincerBilly_Bob_ThorntonOliver_StoneRoman_PolanskiStephen_SommersSpike_LeeZhang_YimouDanny_PangBarry_SonnenfeldMike_NewellGeorge_P._CosmatosOliver_ParkerLawrence_KasanoffBen_AffleckAndrew_DavisAndy_TennantBarry_LevinsonGeorge_P._CosmatosBrian_GibsonBen_SharpsteenMichael_CiminoLen_WisemanPaul_McGuiganGus_Van_SantBetty_ThomasLouis_LeterrierRoger_KumbleSydney_PollackBurr_SteersSimon_WestPhil_LordRoger_MichellNick_ParkJohn_HamburgReginald_HudlinPaul_FeigJoseph_L._MankiewiczFrank_CoraciCarl_FranklinBarbra_StreisandMark_PellingtonLarry_CharlesJohn_GlenCatherine_HardwickeJohn_HerzfeldAnnabel_JankelAndrew_NiccolZhang_YimouJulie_Anne_RobinsonSeth_RogenSngmoo_LeeJean-Pierre_JeunetCurtis_HansonJamel_DebbouzeBrian_HelgelandGordon_ChanM._Night_ShyamalanAsger_LethDavid_FrankelJohn_G._AvildsenDavid_O._RussellAnne_FletcherBruce_BeresfordRobert_ZemeckisLuc_BessonSam_Taylor-JohnsonRobert_RodriguezJoel_SchumacherShawn_LevyPeter_BergPenny_MarshallJames_WanDavid_FincherKen_KwapisDavid_ZuckerWes_CravenRobert_ZemeckisEtan_CohenFrancis_Ford_CoppolaNora_EphronBrian_HelgelandAnthony_MinghellaBobby_FarrellyFrank_MarshallNancy_MeyersTim_StoryMichael_MannTaylor_HackfordRobert_RodriguezPete_TravisJohn_HamburgBobby_FarrellyOliver_StoneJohn_WhitesellGore_VerbinskiBurr_SteersNick_CassavetesDavid_R._EllisSteven_SpielbergJohn_MooreNicholas_StollerPeter_ChelsomJoe_DanteMark_A.Z._DippéKevin_ReynoldsBrad_FurmanJaume_Collet-SerraChristopher_NolanSean_AndersCallan_BrunkerMel_GibsonJohn_GlenNimród_AntalIvan_ReitmanDavid_KoeppAlejandro_AgrestiIain_SoftleyPeter_HedgesPaul_WeilandClint_EastwoodFrancis_Ford_CoppolaMathieu_KassovitzSteven_SpielbergJohn_McTiernanColin_StrauseDonald_PetrieJoan_ChenMarc_LawrenceGreg_MottolaAnne_FletcherWes_CravenJoel_SchumacherOliver_StoneJake_KasdanDiane_KeatonSteven_QualeKelly_MakinMimi_LederBobby_FarrellySteven_BrillSeth_MacFarlaneRussell_MulcahyStephen_DaldryRoger_MichellJim_SheridanChristian_DuguayChris_ColumbusChuck_RussellSam_WeismanJohn_FrankenheimerPeter_HyamsJustin_ChadwickPat_O'ConnorStephen_HopkinsMartin_ScorsesePenny_MarshallOlivier_MegatonFrederik_Du_ChauMichael_Caton-JonesIrwin_WinklerJoseph_KahnHarold_BeckerPaul_VerhoevenSofia_CoppolaBarbet_SchroederStephen_T._KayJuan_Antonio_BayonaElaine_MayWes_AndersonStephen_HerekJohn_CarpenterJean-Pierre_JeunetDennie_GordonCharles_ShyerKen_KwapisUlu_GrosbardWilliam_MalonePaul_WeitzDanny_DeVitoMalcolm_D._LeeJerry_JamesonMic_RodgersChristian_AlvartGary_FlederChristian_DuguayJean-Marie_PoiréDanny_BoyleBrian_RobbinsMarc_F._AdlerPierre_MorelGeoffrey_SaxD.J._CarusoIain_SoftleyRichard_ShepardJoel_CoenPeter_ChanSergei_Bodrov_Jr.Bong_Joon-hoBibo_BergeronJeff_NathansonAlex_ProyasS.S._RajamouliRobert_SchwentkeMichael_LehmannTim_BurtonJoss_WhedonCharles_S._DuttonRichard_LesterPeter_SegalJohn_WooAndy_TennantRobert_LuketicJonathan_LynnRobert_RodriguezDavid_CarsonWong_Kar-waiFrancis_LawrenceYuefeng_SongNorman_JewisonMichael_AptedDavid_MirkinAndy_FickmanLuis_MandokiJohn_PasquinRoman_PolanskiMichael_AptedStephen_HerekLee_DanielsRidley_ScottJohn_CarpenterDavid_TwohyJeb_StuartSteve_MinerGil_KenanPaul_Thomas_AndersonDavid_LelandGary_FlederJ_BlakesonRyan_CooglerBen_AffleckKirk_JonesJoel_CoenJennifer_FlackettRon_HowardPaul_Thomas_AndersonKevin_SmithChristian_DitterCharles_Martin_SmithCatherine_HardwickeNick_CassavetesLes_MayfieldRawson_Marshall_ThurberFyodor_BondarchukJonathan_MostowIrvin_KershnerSteve_PinkCharles_Martin_SmithJohn_FrankenheimerF._Gary_GrayCameron_CroweRob_ReinerScott_HicksMikael_HåfströmAndrew_NiccolAndrew_BergmanKirk_De_MiccoChris_RockTodd_PhillipsWilson_YipJay_RoachTim_BurtonLeslie_H._MartinsonRoland_JofféRichard_DonnerJohn_Lee_HancockRobert_RodriguezSeth_GordonJoel_CoenDavid_FrankelRobert_WiseSeth_GordonMartin_ScorseseRobert_LuketicJudd_ApatowKevin_Rodney_SullivanAnthony_MinghellaCurtis_HansonMike_MitchellFrank_OzRoger_DonaldsonWes_CravenTarsem_SinghRandall_WallaceRandall_WallaceKevin_MunroeMike_TollinWill_GluckNicholas_StollerJohn_Lee_HancockSpike_LeeJudd_ApatowWalt_BeckerPatrick_TatopoulosKen_KwapisDennis_DuganGary_David_GoldbergMike_NewellPaul_W.S._AndersonTobe_HooperJoel_CoenJohn_MooreAndrew_NiccolAlan_PoulLuke_GreenfieldGil_JungerMichael_RitchieSteven_E._de_SouzaRoman_PolanskiCatherine_HardwickeJaume_Collet-SerraMike_NicholsClint_EastwoodAlexandre_AjaMichael_RymerStephen_HopkinsGregory_HoblitHugh_WilsonMike_HodgesKevin_SmithRob_CohenClint_EastwoodScott_MannSusanna_WhiteDanny_DeVitoChris_CarterTommy_O'HaverPeter_LandesmanJohn_SingletonGary_ChapmanCurtis_HansonCraig_MazinAllen_HughesWes_CravenDavid_KoeppAnne_FletcherShekhar_KapurTaylor_HackfordRichard_LoncraineRoger_KumbleKimble_RendallPeter_YatesRobert_RedfordJohn_MiliusJake_KasdanLasse_HallströmLes_MayfieldJean-Marc_ValléeDominic_SenaTerrence_MalickTsui_HarkDavid_AyerBrian_HelgelandLexi_AlexanderPeter_HewittRobert_ZemeckisRonny_YuRidley_ScottRichard_DonnerTaylor_HackfordBille_AugustBrian_De_PalmaMoustapha_AkkadJean-Paul_RappeneauAng_LeeAlejandro_González_IñárrituJoachim_RønningTony_KayeWes_BallKen_ScottMartin_ScorseseDarren_AronofskyHugh_JohnsonSimon_WestHayao_MiyazakiGeorge_Tillman,_Jr.Rand_RavichHugh_HudsonGabriele_MuccinoJustin_ChadwickWarren_BeattyRob_ReinerAndrzej_BartkowiakRaja_GosnellBen_StassenChris_GorakScott_SpeerDavid_R._EllisJoe_CharbanicJonathan_HensleighDanny_CannonBoaz_YakinMike_NewellRichard_MarquandNeil_MarshallStephen_DaldryDavid_WainJon_FavreauJon_TurteltaubBrian_LevantRichard_DonnerJared_HessPaul_FeigSeth_RogenRupert_WainwrightGeorge_Tillman,_Jr.John_LuessenhopJustin_ZackhamJohn_WhitesellDuncan_JonesFrank_MarshallJoel_SchumacherJean-Pierre_JeunetSteven_SpielbergJohn_GatinsDavid_CronenbergLouis_LeterrierSam_RaimiPeter_HowittMartin_ScorseseMiguel_SapochnikShim_Hyung-RaeNorman_JewisonDon_ScardinoMark_DindalTim_RobbinsSteven_SoderberghTom_ReeveFrancis_Ford_CoppolaNanette_BursteinStephen_HerekAriel_VromenSydney_PollackRobert_ZemeckisLewis_GilbertWes_AndersonScott_HicksFrank_MarshallGregory_HoblitJohn_Francis_DaleyBarry_SonnenfeldRob_MarshallDennis_DuganJ.B._RogersJohn_Las

In [164]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

AttributeError: 'list' object has no attribute 'split'

In [163]:
movies.head()

,genres,id,keywords,original_language,overview,release_date,revenue,title,vote_average,vote_count,cast,crew,empty_features,director
0,"[Action, Adventure, Fantasy, Science_Fiction]",19995,"[culture_clash, future, space_war, space_colon...",en,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,2787965087,Avatar,7.2,11800,"[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...","[{'credit_id': '52fe48009251416c750aca23', 'de...",108,[James_Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug_abuse, exotic_island, east_india_...",en,"[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...",53,[Gore_Verbinski]
2,"[Action, Adventure, Crime]",206647,"[spy, based_on_novel, secret_agent, sequel, mi...",en,"[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,880674609,Spectre,6.3,4466,"[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...","[{'credit_id': '54805967c3a36829b5002c41', 'de...",93,[Sam_Mendes]
3,"[Action, Crime, Drama, Thriller]",49026,"[dc_comics, crime_fighter, terrorist, secret_i...",en,"[Following, the, death, of, District, Attorney...",2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,"[Christian_Bale, Michael_Caine, Gary_Oldman, A...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...",183,[Christopher_Nolan]
4,"[Action, Adventure, Science_Fiction]",49529,"[based_on_novel, mars, medallion, space_travel...",en,"[John, Carter, is, a, war-weary,, former, mili...",2012-03-07,284139100,John Carter,6.1,2124,"[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...",46,[Andrew_Stanton]

In [165]:
len(movies['original_language'].unique())

37

In [166]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
og_lang=enc.fit_transform(movies['original_language'])
movies['og_lang']=og_lang

In [167]:
movies.head()

,genres,id,keywords,original_language,overview,release_date,revenue,title,vote_average,vote_count,cast,crew,empty_features,director,og_lang
0,"[Action, Adventure, Fantasy, Science_Fiction]",19995,"[culture_clash, future, space_war, space_colon...",en,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-10,2787965087,Avatar,7.2,11800,"[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...","[{'credit_id': '52fe48009251416c750aca23', 'de...",108,[James_Cameron],7
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug_abuse, exotic_island, east_india_...",en,"[Captain, Barbossa,, long, believed, to, be, d...",2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...",53,[Gore_Verbinski],7
2,"[Action, Adventure, Crime]",206647,"[spy, based_on_novel, secret_agent, sequel, mi...",en,"[A, cryptic, message, from, Bond’s, past, send...",2015-10-26,880674609,Spectre,6.3,4466,"[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...","[{'credit_id': '54805967c3a36829b5002c41', 'de...",93,[Sam_Mendes],7
3,"[Action, Crime, Drama, Thriller]",49026,"[dc_comics, crime_fighter, terrorist, secret_i...",en,"[Following, the, death, of, District, Attorney...",2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,"[Christian_Bale, Michael_Caine, Gary_Oldman, A...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...",183,[Christopher_Nolan],7
4,"[Action, Adventure, Science_Fiction]",49529,"[based_on_novel, mars, medallion, space_travel...",en,"[John, Carter, is, a, war-weary,, former, mili...",2012-03-07,284139100,John Carter,6.1,2124,"[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...",46,[Andrew_Stanton],7

In [174]:
movies['tag']=movies['genres']+movies['keywords']+movies['cast']+movies['director']+movies['overview']

In [188]:
title=movies['title'].apply(lambda x:x.split())
print(title.head())

0                                            [Avatar]
1    [Pirates, of, the, Caribbean:, At, World's, End]
2                                           [Spectre]
3                          [The, Dark, Knight, Rises]
4                                      [John, Carter]
Name: title, dtype: object

In [189]:
df=movies[['id','release_date','revenue','vote_average','vote_count','og_lang','tag']]

In [194]:
df.head()

,id,release_date,revenue,vote_average,vote_count,og_lang,tag,title
0,19995,2009-12-10,2787965087,7.2,11800,7,"[Action, Adventure, Fantasy, Science_Fiction, ...",[Avatar]
1,285,2007-05-19,961000000,6.9,4500,7,"[Adventure, Fantasy, Action, ocean, drug_abuse...","[Pirates, of, the, Caribbean:, At, World's, End]"
2,206647,2015-10-26,880674609,6.3,4466,7,"[Action, Adventure, Crime, spy, based_on_novel...",[Spectre]
3,49026,2012-07-16,1084939099,7.6,9106,7,"[Action, Crime, Drama, Thriller, dc_comics, cr...","[The, Dark, Knight, Rises]"
4,49529,2012-03-07,284139100,6.1,2124,7,"[Action, Adventure, Science_Fiction, based_on_...","[John, Carter]"

In [193]:
df['title']=title

/tmp/ipykernel_7227/2935662674.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['title']=title

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4791 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4791 non-null   int64
 1   release_date  4791 non-null   object
 2   revenue       4791 non-null   int64
 3   vote_average  4791 non-null   float64
 4   vote_count    4791 non-null   int64
 5   og_lang       4791 non-null   int64
 6   tag           4791 non-null   object
 7   title         4791 non-null   object
dtypes: float64(1), int64(4), object(3)
memory usage: 465.9+ KB